
## Manual Alarm Control Panel

  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 20
    delay_time: 0
    trigger_time: 60
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      delay_time: 50
      pending_time: 60
    triggered:
      pending_time: 0